apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weather-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: weather-api 
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
