apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
         app: weather
         tier: backend
         track: stable
    spec:
       containers:
       - name: weather
         image: us.gcr.io/arcusassign/weather:latest
         ports:
          - containerPort: 5000
       - name: redis
         image: redis
         ports:
          - containerPort: 6379
         volumeMounts:
           - name: redis-persistent-storage
             mountPath: /data
       volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: task-pv-claim 
